name = "teste"
main = "worker.js"  # Worker correto como ponto de entrada
compatibility_date = "2024-03-12"

account_id = "cac9af3508f9c8bc41f91c88ad3a6cf2"  # Substitua pelo seu Account ID
workers_dev = true  # Mantém o deploy no workers.dev

modules = true  # Necessário para suportar `export async function onRequest`
